/**
 * @fileoverview Type definitions for MCP prompts and their results.
 */

/**
 * Represents a prompt template with its metadata and arguments.
 * @interface Prompt
 * @property {string} name - The unique identifier of the prompt
 * @property {string} description - Human-readable description of the prompt's purpose
 * @property {Array<{name: string, description: string, required: boolean}>} arguments - List of arguments the prompt accepts
 */
export interface Prompt {
  name: string;
  description: string;
  arguments: {
    name: string;
    description: string;
    required: boolean;
  }[];
}

/**
 * Result returned from executing a prompt.
 * @interface PromptResult
 * @property {unknown[]} messages - Array of messages generated by the prompt
 */
export interface PromptResult {
  messages: unknown[];
}
